yarnPath: .yarn/releases/yarn-3.2.2.cjs

nodeLinker: node-modules

packageExtensions:
  react-notion-x@6.12.11:
    peerDependencies:
      "@babel/runtime": "*"
      webpack: "*"
  react-pdf@5.7.2:
    peerDependencies:
      webpack: "*"
  blog-with-notion@*:
    peerDependencies:
      "@babel/runtime": "*"
      react: "17.2.0"
      react-dom: "17.2.0"
      webpack: "*"
